
# user="wildduck"
# group="wildduck"

ident="ethereal-msa"
processes=1

[smtp]
host="127.0.0.1"
port=5587
secure=false
banner="Welcome to Ethereal MSA"

[tls]
#key="/path/to/server/key.pem"
#ca=["/path/to/server/ca1.pem", "/path/to/server/ca2.pem"]
#cert="/path/to/server/cert.pem"

[log]
level="silly"
# log to syslog if true
# not needed if you run the app as systemd service
syslog=false
authlogExpireDays=30

[dbs]
# mongodb connection string for the main database
mongo="mongodb://127.0.0.1:27017/wildduck"

# redis connection string
redis="redis://127.0.0.1:6379/3"

# Wild Duck allows using different kind of data in different databases
# If you do not provide a database config value, then main database connection
# is used for everything
# You can either use a database name (uses shared connection) or a configutaion
# url (creates a separate connection) for each databases

# Optional database name or connection url for GridFS if you do not want to
# use the main db for storing attachments. Useful if you want
# to use a different mount folder or storage engine
#gridfs="wildduck"

# Optional database name or connection url for users collection if you do not want to
# use the main db for storing user/address data. Useful if you want
# to use a different mount folder or storage engine
#users="wildduck"

# Optional database name or connection url for ZoneMTA queue database. This is
# used to push outbound emails to the sending queue
#sender="zone-mta"

#queued="mail"
